openmrs.root.url: http://localhost.localdomain:8050/openmrs/ws/rest/v1
bahmni.login.url: https://emr.com/bahmni/home/#/login?showLoginMessage
reports.url: https://emr.com/bahmni/reports
reports.json: /var/www/bahmni_config/openmrs/apps/reports/reports.json
dhis.config.directory: /var/www/bahmni_config/dhis2/
dhis.url: http://cmr-dhis2-staging.jembi.org:8080
dhis.user: admin
dhis.password: district
openmrs.db.url: jdbc:mysql://localhost.localdomain/openmrs?user=root&password=password
openelis.db.url: jdbc:mysql://localhost.localdomain/openmrs?user=dbuser&password=dbpassword
log4j.config.file: log4j.properties
server.port: 8040
server.context-path: /dhis-integration/
submission.audit.folder: /opt/dhis-integration/dhis-integration-data